export const CREATE_FORM_REQUEST = 'CREATE_FORM_REQUEST'
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS'
export const CREATE_FORM_FAIL = 'CREATE_FORM_FAIL'

export const MY_FORM_REQUEST = 'MY_FORM_REQUEST'
export const MY_FORM_SUCCESS = 'MY_FORM_SUCCESS'
export const MY_FORM_FAIL = 'MY_FORM_FAIL'

export const ALL_FORM_REQUEST = 'ALL_FORM_REQUEST'
export const ALL_FORM_SUCCESS = 'ALL_FORM_SUCCESS'
export const ALL_FORM_FAIL = 'ALL_FORM_FAIL'

export const UPDATE_FORM_REQUEST = 'UPDATE_FORM_REQUEST'
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS'
export const UPDATE_FORM_RESET = 'UPDATE_FORM_RESET'
export const UPDATE_FORM_FAIL = 'UPDATE_FORM_FAIL'

export const DELETE_FORM_REQUEST = 'DELETE_FORM_REQUEST'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'
export const DELETE_FORM_RESET = 'DELETE_FORM_RESET'
export const DELETE_FORM_FAIL = 'DELETE_FORM_FAIL'

export const FORM_DETAILS_REQUEST = 'FORM_DETAILS_REQUEST'
export const FORM_DETAILS_SUCCESS = 'FORM_DETAILS_SUCCESS'
export const FORM_DETAILS_FAIL = 'FORM_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'