export const ALL_VILLAS_REQUEST = 'ALL_VILLAS_REQUEST'
export const ALL_VILLAS_SUCCESS = 'ALL_VILLAS_SUCCESS'
export const ALL_VILLAS_FAIL = 'ALL_VILLAS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'