export const GET_VILLA_REQUEST = 'GET_VILLA_REQUEST'
export const GET_VILLA_SUCCESS = 'GET_VILLA_SUCCESS'
export const GET_VILLA_FAIL = 'GET_VILLA_FAIL'

export const ADMIN_VILLAS_REQUEST = 'ADMIN_VILLAS_REQUEST'
export const ADMIN_VILLAS_SUCCESS = 'ADMIN_VILLAS_SUCCESS'
export const ADMIN_VILLAS_FAIL = 'ADMIN_VILLAS_FAIL'

export const ALL_VILLAS_REQUEST = 'ALL_VILLAS_REQUEST'
export const ALL_VILLAS_SUCCESS = 'ALL_VILLAS_SUCCESS'
export const ALL_VILLAS_FAIL = 'ALL_VILLAS_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'